### ISSUE TITLE
问题:部署

### ISSUE THREAD

**Issue by Pantyhose-X** [shaoxiongdu/blog#6]
怎么部署在
[freenet网络](https://freenetproject.org/)
[I2P匿名网络](https://geti2p.net/zh/)
[Beaker Browser IPFS 为分布式 Web](https://beakerbrowser.com/)
[ZeroNet网络](https://zeronet.io/zh)

![image](https://user-images.githubusercontent.com/42504385/125800040-4062e719-48af-4690-b6b0-1d765ceb985f.JPG)

**Comment by shaoxiongdu** [comment]
抱歉，没接触过这种部署方式，您可以google关键字 springboot+I2P
